image: python:3.12

stages:
  - unit-test
  - code-coverage

unit-test-job:
  stage: unit-test
  before_script:
#    - pip install --upgrade pip
    - pip install pytest
    - pip install Pillow
    - pip install mss
    - pip install numpy
#    - pip install pywin32

  script:
    - echo "Hello World"
    - cd domain/tests
    - pytest ./test_flappy_bird.py


code-coverage-job:
  stage: code-coverage
  before_script:
    - pip install Pillow
    - pip install mss
    - pip install numpy
#    - pip install pywin32
    - pip install pytest pytest-cov

  script:
    - echo "Hello World"
    - cd domain/tests
    - pytest --cov --cov-report term --cov-report xml:coverage.xml

#  coverage: '/TOTAL.*\s([.\d]+)%/'
  coverage: '/builds/rkeijzer/personal-ip/domain/source/flappy_tester.py.*\s([.\d]+)%/'

  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml