image: python:3.12

stages:
  - sample-stage

sample-job:
  stage: sample-stage
  before_script:
    - pip install --upgrade pip
    - pip install pytest
    - pip install Pillow
    - pip install mss
    - pip install numpy
    - pip install pywin32

  script:
    - echo "Hello World"
    - cd domain/tests
    - pytest ./test_flappy_bird.py
